// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StripeWebApp.Models;

#nullable disable

namespace StripeWebApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StripeWebApp.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://monochrome-watches.com/wp-content/uploads/2023/08/Jacob-and-Co-The-World-Is-Yours-Dual-Time-Zone-Watch-1.jpg",
                            Name = "Jacob & Co THE WORLD IS YOURS DUAL TIME ZONE",
                            PriceID = "price_1QV644FCRscjNLWmDLp9BYMl"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://cdn.media.amplience.net/i/frasersdev/63708340_o.jpg?v=220121212030",
                            Name = "Jordan T-Shirt",
                            PriceID = "price_1QV5xOFCRscjNLWm2AAOVYjj"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://mir-s3-cdn-cf.behance.net/project_modules/1400/5be63c100114067.5f024a0a667e0.jpg",
                            Name = "Summer T-Shirt",
                            PriceID = "price_1QV67AFCRscjNLWmGJIX1IHH"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
